name: Update license year

on:
  schedule:
    - cron: '0 3 1 1 *'   # каждый год 1 января в 03:00 UTC
  workflow_dispatch:      # для ручного запуска

jobs:
  update-license-year:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # <-- обязательно для создания коммита и пуша
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}   # <-- эта строка обязательна
      
      - name: Update license year
        uses: FantasticFiasco/action-update-license-year@v3
        with:
          license-file: 'LICENSE.md'
